package com.allianz.labportal.model;
// default package
// Generated Jul 3, 2017 11:54:32 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AssignToDoctor generated by hbm2java
 */
@Entity
@Table(name = "assign_to_doctor", catalog = "allianz_lab_portal")
public class AssignToDoctor implements java.io.Serializable {

	private Integer id;
	private Integer tokenId;
	private String doctor;

	public AssignToDoctor() {
	}

	public AssignToDoctor(Integer tokenId, String doctor) {
		this.tokenId = tokenId;
		this.doctor = doctor;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "token_id")
	public Integer getTokenId() {
		return this.tokenId;
	}

	public void setTokenId(Integer tokenId) {
		this.tokenId = tokenId;
	}

	@Column(name = "doctor")
	public String getDoctor() {
		return this.doctor;
	}

	public void setDoctor(String doctor) {
		this.doctor = doctor;
	}

}
