package com.allianz.labportal.model;
// default package
// Generated Jul 3, 2017 11:54:32 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name = "department", catalog = "allianz_lab_portal")
public class Department implements java.io.Serializable {

	private Integer id;
	private String departmentName;
	private Set<Subdepartment> subdepartments = new HashSet<Subdepartment>(0);

	public Department() {
	}

	public Department(String departmentName, Set<Subdepartment> subdepartments) {
		this.departmentName = departmentName;
		this.subdepartments = subdepartments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "department_name", length = 45)
	public String getDepartmentName() {
		return this.departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "department")
	public Set<Subdepartment> getSubdepartments() {
		return this.subdepartments;
	}

	public void setSubdepartments(Set<Subdepartment> subdepartments) {
		this.subdepartments = subdepartments;
	}

}
