package com.allianz.labportal.model;
// default package
// Generated Jul 3, 2017 11:54:32 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Lab generated by hbm2java
 */
@Entity
@Table(name = "lab", catalog = "allianz_lab_portal")
public class Lab implements java.io.Serializable {

	private Integer id;
	private Integer labType;
	private Integer labCategory;
	private String labName;
	private String district;
	private String branch;
	private String division;
	private String address;
	private String email;
	private String contactNo;
	private String contactNo3;
	private String contactNo2;
	private String fax;

	public Lab() {
	}

	public Lab(Integer labType, Integer labCategory, String labName, String district, String branch, String division,
			String address, String email, String contactNo, String contactNo3, String contactNo2, String fax) {
		this.labType = labType;
		this.labCategory = labCategory;
		this.labName = labName;
		this.district = district;
		this.branch = branch;
		this.division = division;
		this.address = address;
		this.email = email;
		this.contactNo = contactNo;
		this.contactNo3 = contactNo3;
		this.contactNo2 = contactNo2;
		this.fax = fax;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "lab_type")
	public Integer getLabType() {
		return this.labType;
	}

	public void setLabType(Integer labType) {
		this.labType = labType;
	}

	@Column(name = "lab_category")
	public Integer getLabCategory() {
		return this.labCategory;
	}

	public void setLabCategory(Integer labCategory) {
		this.labCategory = labCategory;
	}

	@Column(name = "lab_name", length = 45)
	public String getLabName() {
		return this.labName;
	}

	public void setLabName(String labName) {
		this.labName = labName;
	}

	@Column(name = "district", length = 45)
	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	@Column(name = "branch", length = 45)
	public String getBranch() {
		return this.branch;
	}

	public void setBranch(String branch) {
		this.branch = branch;
	}

	@Column(name = "division", length = 45)
	public String getDivision() {
		return this.division;
	}

	public void setDivision(String division) {
		this.division = division;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "contact_no", length = 45)
	public String getContactNo() {
		return this.contactNo;
	}

	public void setContactNo(String contactNo) {
		this.contactNo = contactNo;
	}

	@Column(name = "contact_no3", length = 45)
	public String getContactNo3() {
		return this.contactNo3;
	}

	public void setContactNo3(String contactNo3) {
		this.contactNo3 = contactNo3;
	}

	@Column(name = "contact_no2", length = 45)
	public String getContactNo2() {
		return this.contactNo2;
	}

	public void setContactNo2(String contactNo2) {
		this.contactNo2 = contactNo2;
	}

	@Column(name = "fax", length = 45)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

}
