package com.allianz.labportal.model;
// default package
// Generated Jul 3, 2017 11:54:32 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Register generated by hbm2java
 */
@Entity
@Table(name = "register", catalog = "allianz_lab_portal")
public class Register implements java.io.Serializable {

	private Integer id;
	private String userType;
	private String doctorName;
	private String address;
	private String doctorTelephone;
	private String dob;
	private String doctorEmail;
	private Byte mediCouncilRegistered;
	private String dateOfRegistration;
	private Date date;
	private String labName;
	private String labAddress;
	private String labTelephone;
	private String labEmail;
	private Byte accessType;

	public Register() {
	}

	public Register(String userType, String doctorName, String address, String doctorTelephone, String dob,
			String doctorEmail, Byte mediCouncilRegistered, String dateOfRegistration, Date date, String labName,
			String labAddress, String labTelephone, String labEmail, Byte accessType) {
		this.userType = userType;
		this.doctorName = doctorName;
		this.address = address;
		this.doctorTelephone = doctorTelephone;
		this.dob = dob;
		this.doctorEmail = doctorEmail;
		this.mediCouncilRegistered = mediCouncilRegistered;
		this.dateOfRegistration = dateOfRegistration;
		this.date = date;
		this.labName = labName;
		this.labAddress = labAddress;
		this.labTelephone = labTelephone;
		this.labEmail = labEmail;
		this.accessType = accessType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "userType", length = 45)
	public String getUserType() {
		return this.userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	@Column(name = "doctorName", length = 45)
	public String getDoctorName() {
		return this.doctorName;
	}

	public void setDoctorName(String doctorName) {
		this.doctorName = doctorName;
	}

	@Column(name = "address", length = 45)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "doctorTelephone", length = 45)
	public String getDoctorTelephone() {
		return this.doctorTelephone;
	}

	public void setDoctorTelephone(String doctorTelephone) {
		this.doctorTelephone = doctorTelephone;
	}

	@Column(name = "dob", length = 45)
	public String getDob() {
		return this.dob;
	}

	public void setDob(String dob) {
		this.dob = dob;
	}

	@Column(name = "doctorEmail", length = 45)
	public String getDoctorEmail() {
		return this.doctorEmail;
	}

	public void setDoctorEmail(String doctorEmail) {
		this.doctorEmail = doctorEmail;
	}

	@Column(name = "medi_council_registered")
	public Byte getMediCouncilRegistered() {
		return this.mediCouncilRegistered;
	}

	public void setMediCouncilRegistered(Byte mediCouncilRegistered) {
		this.mediCouncilRegistered = mediCouncilRegistered;
	}

	@Column(name = "date_of_registration", length = 45)
	public String getDateOfRegistration() {
		return this.dateOfRegistration;
	}

	public void setDateOfRegistration(String dateOfRegistration) {
		this.dateOfRegistration = dateOfRegistration;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "labName", length = 45)
	public String getLabName() {
		return this.labName;
	}

	public void setLabName(String labName) {
		this.labName = labName;
	}

	@Column(name = "labAddress", length = 45)
	public String getLabAddress() {
		return this.labAddress;
	}

	public void setLabAddress(String labAddress) {
		this.labAddress = labAddress;
	}

	@Column(name = "labTelephone", length = 45)
	public String getLabTelephone() {
		return this.labTelephone;
	}

	public void setLabTelephone(String labTelephone) {
		this.labTelephone = labTelephone;
	}

	@Column(name = "labEmail", length = 45)
	public String getLabEmail() {
		return this.labEmail;
	}

	public void setLabEmail(String labEmail) {
		this.labEmail = labEmail;
	}

	@Column(name = "accessType")
	public Byte getAccessType() {
		return this.accessType;
	}

	public void setAccessType(Byte accessType) {
		this.accessType = accessType;
	}

}
