package com.allianz.labportal.model;
// default package
// Generated Jul 3, 2017 11:54:32 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Subdepartment generated by hbm2java
 */
@Entity
@Table(name = "subdepartment", catalog = "allianz_lab_portal")
public class Subdepartment implements java.io.Serializable {

	private Integer id;
	private Department department;
	private String subdepartmentName;

	public Subdepartment() {
	}

	public Subdepartment(Department department, String subdepartmentName) {
		this.department = department;
		this.subdepartmentName = subdepartmentName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "department_id")
	public Department getDepartment() {
		return this.department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	@Column(name = "subdepartment_name", length = 45)
	public String getSubdepartmentName() {
		return this.subdepartmentName;
	}

	public void setSubdepartmentName(String subdepartmentName) {
		this.subdepartmentName = subdepartmentName;
	}

}
