package com.allianz.labportal.model;
// default package
// Generated Jul 3, 2017 11:54:32 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SubLab generated by hbm2java
 */
@Entity
@Table(name = "sub_lab", catalog = "allianz_lab_portal")
public class SubLab implements java.io.Serializable {

	private Integer id;
	private String sublabName;
	private String address;
	private Integer headLabId;

	public SubLab() {
	}

	public SubLab(String sublabName, String address, Integer headLabId) {
		this.sublabName = sublabName;
		this.address = address;
		this.headLabId = headLabId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "sublab_name", length = 45)
	public String getSublabName() {
		return this.sublabName;
	}

	public void setSublabName(String sublabName) {
		this.sublabName = sublabName;
	}

	@Column(name = "address", length = 45)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "head_lab_id")
	public Integer getHeadLabId() {
		return this.headLabId;
	}

	public void setHeadLabId(Integer headLabId) {
		this.headLabId = headLabId;
	}

}
