package com.allianz.labportal.model;
// default package
// Generated Jul 3, 2017 11:54:32 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UploadReportsFromLab generated by hbm2java
 */
@Entity
@Table(name = "upload_reports_from_lab", catalog = "allianz_lab_portal")
public class UploadReportsFromLab implements java.io.Serializable {

	private Integer id;
	private String labName;
	private Integer tokenId;
	private String uploadStatus;
	private String report;
	private String filepath;
	private Integer requestReportCount;
	private Integer uploadReportCount;
	private Integer pendingReportCount;

	public UploadReportsFromLab() {
	}

	public UploadReportsFromLab(String labName, Integer tokenId, String uploadStatus, String report, String filepath,
			Integer requestReportCount, Integer uploadReportCount, Integer pendingReportCount) {
		this.labName = labName;
		this.tokenId = tokenId;
		this.uploadStatus = uploadStatus;
		this.report = report;
		this.filepath = filepath;
		this.requestReportCount = requestReportCount;
		this.uploadReportCount = uploadReportCount;
		this.pendingReportCount = pendingReportCount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "lab_name")
	public String getLabName() {
		return this.labName;
	}

	public void setLabName(String labName) {
		this.labName = labName;
	}

	@Column(name = "token_id")
	public Integer getTokenId() {
		return this.tokenId;
	}

	public void setTokenId(Integer tokenId) {
		this.tokenId = tokenId;
	}

	@Column(name = "upload_status")
	public String getUploadStatus() {
		return this.uploadStatus;
	}

	public void setUploadStatus(String uploadStatus) {
		this.uploadStatus = uploadStatus;
	}

	@Column(name = "report")
	public String getReport() {
		return this.report;
	}

	public void setReport(String report) {
		this.report = report;
	}

	@Column(name = "filepath")
	public String getFilepath() {
		return this.filepath;
	}

	public void setFilepath(String filepath) {
		this.filepath = filepath;
	}

	@Column(name = "request_report_count")
	public Integer getRequestReportCount() {
		return this.requestReportCount;
	}

	public void setRequestReportCount(Integer requestReportCount) {
		this.requestReportCount = requestReportCount;
	}

	@Column(name = "upload_report_count")
	public Integer getUploadReportCount() {
		return this.uploadReportCount;
	}

	public void setUploadReportCount(Integer uploadReportCount) {
		this.uploadReportCount = uploadReportCount;
	}

	@Column(name = "pending_report_count")
	public Integer getPendingReportCount() {
		return this.pendingReportCount;
	}

	public void setPendingReportCount(Integer pendingReportCount) {
		this.pendingReportCount = pendingReportCount;
	}

}
