package com.allianz.labportal.model;
// default package
// Generated Jul 3, 2017 11:54:32 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Uploadreportsfromdoctor generated by hbm2java
 */
@Entity
@Table(name = "uploadreportsfromdoctor", catalog = "allianz_lab_portal")
public class Uploadreportsfromdoctor implements java.io.Serializable {

	private Integer id;
	private Integer tokenId;
	private Integer doctorId;
	private String doctorName;
	private String uploadStatus;
	private String filepath;
	private String reports;

	public Uploadreportsfromdoctor() {
	}

	public Uploadreportsfromdoctor(Integer tokenId, Integer doctorId, String doctorName, String uploadStatus,
			String filepath, String reports) {
		this.tokenId = tokenId;
		this.doctorId = doctorId;
		this.doctorName = doctorName;
		this.uploadStatus = uploadStatus;
		this.filepath = filepath;
		this.reports = reports;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "tokenId")
	public Integer getTokenId() {
		return this.tokenId;
	}

	public void setTokenId(Integer tokenId) {
		this.tokenId = tokenId;
	}

	@Column(name = "doctorId")
	public Integer getDoctorId() {
		return this.doctorId;
	}

	public void setDoctorId(Integer doctorId) {
		this.doctorId = doctorId;
	}

	@Column(name = "doctor_name")
	public String getDoctorName() {
		return this.doctorName;
	}

	public void setDoctorName(String doctorName) {
		this.doctorName = doctorName;
	}

	@Column(name = "upload_status")
	public String getUploadStatus() {
		return this.uploadStatus;
	}

	public void setUploadStatus(String uploadStatus) {
		this.uploadStatus = uploadStatus;
	}

	@Column(name = "filepath")
	public String getFilepath() {
		return this.filepath;
	}

	public void setFilepath(String filepath) {
		this.filepath = filepath;
	}

	@Column(name = "reports")
	public String getReports() {
		return this.reports;
	}

	public void setReports(String reports) {
		this.reports = reports;
	}

}
