package com.allianz.labportal.model;
// default package
// Generated Jul 3, 2017 11:54:32 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "allianz_lab_portal")
public class User implements java.io.Serializable {

	private Integer id;
	private String username;
	private String password;
	private String fullName;
	private String email;
	private String nic;
	private Integer userTypeId;
	private String branch;
	private Integer labId;
	private String labName;
	private Date createdDate;
	private String contactNo;
	private Date passwordModifyDate;
	private boolean firstLoginStatus;

	public User() {
	}

	public User(String username, boolean firstLoginStatus) {
		this.username = username;
		this.firstLoginStatus = firstLoginStatus;
	}

	public User(String username, String password, String fullName, String email, String nic, Integer userTypeId,
			String branch, Integer labId, String labName, Date createdDate, String contactNo, Date passwordModifyDate,
			boolean firstLoginStatus) {
		this.username = username;
		this.password = password;
		this.fullName = fullName;
		this.email = email;
		this.nic = nic;
		this.userTypeId = userTypeId;
		this.branch = branch;
		this.labId = labId;
		this.labName = labName;
		this.createdDate = createdDate;
		this.contactNo = contactNo;
		this.passwordModifyDate = passwordModifyDate;
		this.firstLoginStatus = firstLoginStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "username", nullable = false, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "full_name")
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "nic", length = 45)
	public String getNic() {
		return this.nic;
	}

	public void setNic(String nic) {
		this.nic = nic;
	}

	@Column(name = "user_type_id")
	public Integer getUserTypeId() {
		return this.userTypeId;
	}

	public void setUserTypeId(Integer userTypeId) {
		this.userTypeId = userTypeId;
	}

	@Column(name = "branch")
	public String getBranch() {
		return this.branch;
	}

	public void setBranch(String branch) {
		this.branch = branch;
	}

	@Column(name = "lab_id")
	public Integer getLabId() {
		return this.labId;
	}

	public void setLabId(Integer labId) {
		this.labId = labId;
	}

	@Column(name = "lab_name")
	public String getLabName() {
		return this.labName;
	}

	public void setLabName(String labName) {
		this.labName = labName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "contact_no", length = 45)
	public String getContactNo() {
		return this.contactNo;
	}

	public void setContactNo(String contactNo) {
		this.contactNo = contactNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "passwordModifyDate", length = 19)
	public Date getPasswordModifyDate() {
		return this.passwordModifyDate;
	}

	public void setPasswordModifyDate(Date passwordModifyDate) {
		this.passwordModifyDate = passwordModifyDate;
	}

	@Column(name = "first_login_status", nullable = false)
	public boolean isFirstLoginStatus() {
		return this.firstLoginStatus;
	}

	public void setFirstLoginStatus(boolean firstLoginStatus) {
		this.firstLoginStatus = firstLoginStatus;
	}

}
